version: "3"

services:
  web:
    container_name: web
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - "./client/.env"
    ports:
      - "8000:8000"
    volumes:
      - "/app/node_modules"
      - "./client:/app"
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: ./wp-api
      dockerfile: Dockerfile.dev
      args:
        APACHE_RUN_USER: daemon
        WP_DB_NAME: wordpress
        WP_DB_USER: wordpress
        WP_DB_PASS: wordpress
        WP_DB_HOST: db
        WP_DB_PORT: 3306
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./wp-api/conf/ports.conf:/etc/apache2/ports.conf"
      - "./wp-api/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      - "./wp-api/conf/.htaccess:/var/www/html/wordpress/.htaccess"
      # - "./wp-api/wp-content:/var/www/html/wordpress/wp-content" # Watch permissions
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
