version: "3"

services:
  api:
    container_name: api
    build:
      context: ./wp-api
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - "./wp-api/conf/ports.conf:/etc/apache2/ports.conf"
      - "./wp-api/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
